import { DomainError, err, ok, type Result } from '@merit/shared';
import type { AffinityPaths } from './affinity-path.js';
import { AFFINITY_PATH_LABEL } from './affinity-path.js';
import type { AskCalibration } from './ask-calibration.js';
import type { FinancialTrend } from './financial-trend.js';
import type { FunderReachability, ReachabilityGrant } from './funder-reachability.js';

/**
 * The funder brief: what the evidence says, with the evidence named, and an explicit statement
 * of what it does not say.
 *
 * This is composed arithmetically from filing rows, not generated by a model. The product rule
 * is that every claim traces to a filing; a template that can only speak in sentences built
 * from rows it is holding satisfies that rule structurally, where a model would have to be
 * policed into satisfying it. The model arrives at S4, where the task is drafting rather than
 * reporting.
 */

/** Where a claim's evidence lives. A union rather than a nullable bag: the three sources are
 *  cited differently and a reader must be able to tell which one they are being shown. */
export type Citation =
  | {
      readonly kind: 'filings';
      readonly funderEin: string;
      readonly irsObjectIds: readonly string[];
      readonly taxYears: readonly number[];
    }
  | { readonly kind: 'registry'; readonly ein: string }
  | { readonly kind: 'propublica'; readonly ein: string; readonly taxYears: readonly number[] };

export type BriefTopic = 'giving' | 'openness' | 'geography' | 'program' | 'ask' | 'proximity' | 'finances';

export interface BriefClaim {
  readonly id: string;
  readonly topic: BriefTopic;
  readonly statement: string;
  /** Never empty. `validateBrief` rejects a brief in which it is. */
  readonly citations: readonly Citation[];
}

export interface FunderBrief {
  readonly funderName: string;
  readonly claims: readonly BriefClaim[];
  /** What this evidence does not support. Always populated. */
  readonly limitations: readonly string[];
}

export interface FunderBriefInput {
  readonly funderEin: string;
  readonly funderName: string;
  readonly organizationName: string;
  readonly organizationState: string;
  readonly grants: readonly ReachabilityGrant[];
  readonly reachability: FunderReachability;
  readonly calibration: AskCalibration;
  readonly affinity: AffinityPaths;
  /** Null when ProPublica could not be reached. The brief says so rather than going quiet. */
  readonly financials: FinancialTrend | null;
}

/** A claim reached the brief without evidence behind it. A bug in composition, caught before
 *  anything renders -- the product rule is that this cannot happen. */
export class UncitedClaim extends DomainError {
  readonly code = 'uncited_claim';
}

/**
 * Deterministic money formatting. `toLocaleString` varies with the host's ICU data, and a
 * claim's wording must not depend on which machine composed it.
 */
const dollars = (cents: number): string => {
  const whole = Math.round(cents / 100);
  const digits = String(Math.abs(whole));
  const grouped = digits.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  return `${whole < 0 ? '-' : ''}$${grouped}`;
};

const percent = (fraction: number): string => `${Math.round(fraction * 100)}%`;

const citeFilings = (funderEin: string, grants: readonly ReachabilityGrant[]): Citation => ({
  kind: 'filings',
  funderEin,
  irsObjectIds: [...new Set(grants.map((grant) => grant.irsObjectId))].sort(),
  taxYears: [...new Set(grants.map((grant) => grant.taxYear))].sort((a, b) => a - b),
});

const BASIS_WORDING: Readonly<Record<AskCalibration['basis'], string>> = {
  first_grants_in_size_band: 'first grants to organisations of a comparable size',
  first_grants_any_size: 'first grants to organisations of any size, none being comparable in size',
  all_grants: 'grants on file, no first grant to a new grantee being observable in the years ingested',
  no_evidence: 'no evidence',
};

export const composeFunderBrief = (input: FunderBriefInput): FunderBrief => {
  const claims: BriefClaim[] = [];
  const { reachability, funderEin, funderName } = input;

  if (reachability.totalGrants > 0) {
    const years = reachability.years;
    const span =
      years.length === 1
        ? `in ${years[0]!.taxYear}`
        : `between ${years[0]!.taxYear} and ${years[years.length - 1]!.taxYear}`;
    claims.push({
      id: 'giving',
      topic: 'giving',
      statement:
        `${funderName} made ${reachability.totalGrants} grants totalling ` +
        `${dollars(reachability.totalCents)} to ${reachability.distinctGrantees} ` +
        `${reachability.distinctGrantees === 1 ? 'organisation' : 'organisations'} ${span}.`,
      citations: [citeFilings(funderEin, input.grants)],
    });
  }

  const comparableYears = reachability.years.filter((year) => year.turnover !== null);
  const latestComparable = comparableYears[comparableYears.length - 1];
  if (latestComparable !== undefined) {
    claims.push({
      id: 'openness',
      topic: 'openness',
      statement:
        `In ${latestComparable.taxYear} it funded ${latestComparable.granteeCount} ` +
        `${latestComparable.granteeCount === 1 ? 'organisation' : 'organisations'}, of which ` +
        `${latestComparable.newGranteeCount} had not been funded the previous year on file, and ` +
        `${latestComparable.departedGranteeCount} of the previous year's grantees did not return.`,
      citations: [
        citeFilings(
          funderEin,
          input.grants.filter((grant) => grant.taxYear === latestComparable.taxYear),
        ),
      ],
    });
  }

  const largestState = reachability.geographicSpread.states[0];
  if (largestState !== undefined) {
    const home = reachability.geographicSpread.states.find(
      (state) => state.state === input.organizationState,
    );
    const homeClause =
      home === undefined
        ? ` No grant on file went to an organisation in ${input.organizationState}.`
        : ` ${percent(home.share)} went to organisations in ${input.organizationState}.`;
    claims.push({
      id: 'geography',
      topic: 'geography',
      statement:
        `Its giving reaches ${reachability.geographicSpread.distinctStates} ` +
        `${reachability.geographicSpread.distinctStates === 1 ? 'state' : 'states'}, the largest share ` +
        `${percent(largestState.share)} to organisations in ${largestState.state}.${homeClause}`,
      citations: [citeFilings(funderEin, input.grants)],
    });
  }

  const largestProgram = reachability.programMix[0];
  if (largestProgram !== undefined) {
    claims.push({
      id: 'program',
      topic: 'program',
      statement:
        `Of its grantees whose program area is on the registry, ${percent(largestProgram.share)} work in ` +
        `${largestProgram.label}.`,
      citations: [citeFilings(funderEin, input.grants), { kind: 'registry', ein: funderEin }],
    });
  }

  if (input.calibration.recommendedCents !== null && input.calibration.basis !== 'no_evidence') {
    const range =
      input.calibration.lowCents === null || input.calibration.highCents === null
        ? ''
        : ` Comparable asks ran from ${dollars(input.calibration.lowCents)} to ${dollars(input.calibration.highCents)}.`;
    claims.push({
      id: 'ask',
      topic: 'ask',
      statement:
        `A first ask of ${dollars(input.calibration.recommendedCents)} is in line with what this funder ` +
        `has given, calculated from ${input.calibration.sampleSize} ` +
        `${BASIS_WORDING[input.calibration.basis]}.${range}`,
      citations: [citeFilings(funderEin, input.grants)],
    });
  }

  if (input.affinity.paths.length > 0) {
    claims.push({
      id: 'proximity',
      topic: 'proximity',
      statement:
        `${input.affinity.paths.length} of this funder's grantees share a funder with organisations ` +
        `comparable to ${input.organizationName}, across ` +
        `${input.affinity.distinctIntermediaryFunders} shared ` +
        `${input.affinity.distinctIntermediaryFunders === 1 ? 'funder' : 'funders'}. This is ` +
        `${AFFINITY_PATH_LABEL} and nothing more.`,
      citations: [citeFilings(funderEin, input.grants)],
    });
  }

  const financials = input.financials;
  if (financials !== null && financials.latest !== null) {
    const direction =
      financials.grantsPaid.direction === 'unknown'
        ? 'cannot be read from the years available'
        : `has been ${financials.grantsPaid.direction}`;
    const payout =
      financials.payoutRate === null
        ? ''
        : ` In ${financials.latest.taxYear} it paid out ${percent(financials.payoutRate)} of its assets.`;
    claims.push({
      id: 'finances',
      topic: 'finances',
      statement: `Its reported grantmaking ${direction} across the filings ProPublica holds.${payout}`,
      citations: [
        {
          kind: 'propublica',
          ein: funderEin,
          taxYears: financials.years.map((year) => year.taxYear),
        },
      ],
    });
  }

  return { funderName, claims, limitations: limitationsOf(input) };
};

/**
 * What the evidence does not support, stated rather than left to be inferred. The first three
 * are unconditional: they are true of every funder brief this system can produce.
 */
const limitationsOf = (input: FunderBriefInput): readonly string[] => {
  const limitations: string[] = [
    'This is a record of what the funder has done. It does not tell you what it will do, and a ' +
      'funder is free to change its priorities without filing anything to say so.',
    'Public filings name who was funded. They never name who applied and was declined, so nothing ' +
      'here can tell you your chances — there is no denominator to work from.',
    'Merit will not contact this funder and will not submit anything on your behalf.',
  ];

  if (input.reachability.years.length === 1) {
    limitations.push(
      'Only one filing year is on file for this funder, so nothing here describes a trend and ' +
        'turnover cannot be computed at all.',
    );
  }

  if (input.financials === null) {
    limitations.push(
      'The financial trend could not be retrieved from ProPublica, so this brief says nothing ' +
        'about whether the funder’s giving capacity is growing or shrinking.',
    );
  }

  if (input.reachability.programMixUnknownGrantees > 0) {
    limitations.push(
      `${input.reachability.programMixUnknownGrantees} of this funder’s grantees could not be ` +
        'matched to a program area in the registry, so the program mix describes only the ' +
        'grantees that were matched.',
    );
  }

  if (input.reachability.geographicSpread.unstatedGrantCount > 0) {
    limitations.push(
      `${input.reachability.geographicSpread.unstatedGrantCount} grants carry no recipient state ` +
        'on the filing, so the geographic spread is a floor rather than a complete picture.',
    );
  }

  if (input.calibration.basis === 'all_grants') {
    limitations.push(
      'No first grant to a new grantee was observable in the years ingested, so the suggested ask ' +
        'is drawn from every grant on file — including renewals to organisations already inside.',
    );
  }

  if (input.calibration.basis === 'first_grants_any_size') {
    limitations.push(
      'No organisation of a comparable size appears among this funder’s new grantees, so the ' +
        'suggested ask is drawn from first grants to organisations of every size.',
    );
  }

  return limitations;
};

/**
 * The rule enforced as a value: no claim renders without a source behind it. Composition is
 * supposed to guarantee this, so a failure here is a bug -- but a product rule this load-bearing
 * gets checked rather than trusted.
 */
export const validateBrief = (brief: FunderBrief): Result<FunderBrief, UncitedClaim> => {
  for (const claim of brief.claims) {
    if (claim.citations.length === 0) {
      return err(
        new UncitedClaim('a brief claim carries no citation', {
          claimId: claim.id,
          funder: brief.funderName,
        }),
      );
    }
    for (const citation of claim.citations) {
      if (citation.kind === 'filings' && citation.irsObjectIds.length === 0) {
        return err(
          new UncitedClaim('a brief claim cites filings but names none', {
            claimId: claim.id,
            funder: brief.funderName,
          }),
        );
      }
    }
  }
  return ok(brief);
};
