import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { unwrapOrThrow } from '@merit/shared';
import { parseGrantsGovDate, toFederalOpportunity } from './opportunity-mapper.js';
import { GrantsGovOpportunitySchema } from './opportunity.schema.js';

/**
 * Real payloads the live Grants.gov API returned, recorded to `tests/fixtures/grants-gov/` and
 * regenerated by the nightly contract test. A hand-written payload would test the feed we
 * imagined rather than the one that exists -- which is exactly the mistake the Merit.md
 * appendix exists to prevent.
 */
const FIXTURES = join(process.cwd(), 'tests/fixtures/grants-gov');

const payload = (id: string) =>
  GrantsGovOpportunitySchema.parse(
    JSON.parse(readFileSync(join(FIXTURES, `fetch-opportunity-${id}.json`), 'utf8')),
  );

const mapped = (id: string) => unwrapOrThrow(toFederalOpportunity(payload(id)));

/** HHS-2026-ACF-OCS-EAH-0027, open to 501(c)(3) nonprofits, with every award figure stated. */
const ACF_HOUSING = '362839';
/** PAR-25-003, open to state governments only, award floor stated as 0 and no estimated total. */
const FDA_ANIMAL_FOOD = '359816';
/** HRSA-26-045, the Delta States announcement, whose eligibility prose names eight states. */
const HRSA_DELTA = '362942';

describe('toFederalOpportunity', () => {
  it('keeps the federal program number, which is the join key to award history', () => {
    expect(mapped(HRSA_DELTA).programNumbers).toEqual(['93.619']);
  });

  it('reads the applicant type codes screening decides on', () => {
    expect(mapped(FDA_ANIMAL_FOOD).applicantTypeCodes).toEqual(['00']);
  });

  it('keeps the eligibility prose, the only place geography is ever stated', () => {
    expect(mapped(HRSA_DELTA).eligibilityText).toContain('Mississippi Delta Region States');
  });

  it('converts award figures from whole dollars to integer cents', () => {
    const opportunity = mapped(ACF_HOUSING);

    expect(opportunity.awardCeilingCents).toBe(300_000_00);
    expect(opportunity.awardFloorCents).toBe(150_000_00);
    expect(opportunity.estimatedFundingCents).toBe(2_100_000_00);
    expect(opportunity.expectedAwardCount).toBe(7);
  });

  it('reads a stated zero floor as zero, not as missing', () => {
    expect(mapped(FDA_ANIMAL_FOOD).awardFloorCents).toBe(0);
  });

  it('reads an absent estimated total as not stated', () => {
    expect(mapped(FDA_ANIMAL_FOOD).estimatedFundingCents).toBeNull();
  });

  it('normalises the feed’s own date wording to ISO', () => {
    expect(mapped(ACF_HOUSING).closeDate).toBe('2026-08-24');
    expect(mapped(ACF_HOUSING).openDate).toBe('2026-07-24');
  });

  it('keeps only the full announcement’s attachments, which is where the rubric is', () => {
    // HRSA-26-045 has a "Full Announcement" folder and an "Other Supporting Documents" folder.
    expect(mapped(HRSA_DELTA).attachments.length).toBeGreaterThan(0);
  });

  it('keeps each attachment’s media type and file name, so S4 can pick the PDF to read', () => {
    // Without these two fields the rubric extractor cannot tell a 60-page NOFO from a budget
    // spreadsheet, and `pdftotext` would be handed a file it cannot read.
    const attachment = mapped(HRSA_DELTA).attachments[0];

    expect(attachment).toMatchObject({ mimeType: 'application/pdf' });
    expect(attachment?.fileName).toContain('HRSA-26-045');
  });

  it('refuses an unrecognised status rather than calling a closed announcement open', () => {
    const raw = payload(ACF_HOUSING);
    const result = toFederalOpportunity({ ...raw, data: { ...raw.data, ost: 'SOMETHING_NEW' } });

    expect(result.ok).toBe(false);
  });

  it('refuses an award figure that is neither a number nor "none"', () => {
    const raw = payload(ACF_HOUSING);
    const result = toFederalOpportunity({
      ...raw,
      data: { ...raw.data, synopsis: { ...raw.data.synopsis, awardCeiling: 'to be determined' } },
    });

    expect(result.ok).toBe(false);
  });

  it('reads "none" as not stated, because the feed says it that way', () => {
    const raw = payload(ACF_HOUSING);
    const result = toFederalOpportunity({
      ...raw,
      data: { ...raw.data, synopsis: { ...raw.data.synopsis, awardCeiling: 'none' } },
    });

    expect(result.ok ? result.value.awardCeilingCents : 0).toBeNull();
  });
});

describe('parseGrantsGovDate', () => {
  it('reads the search hit format', () => {
    expect(unwrapOrThrow(parseGrantsGovDate('08/24/2026'))).toBe('2026-08-24');
  });

  it('reads the detail format, in both daylight and standard time', () => {
    expect(unwrapOrThrow(parseGrantsGovDate('Aug 24, 2026 12:00:00 AM EDT'))).toBe('2026-08-24');
    expect(unwrapOrThrow(parseGrantsGovDate('Jan 07, 2027 12:00:00 AM EST'))).toBe('2027-01-07');
  });

  it('reads a date with no leading zero', () => {
    expect(unwrapOrThrow(parseGrantsGovDate('Jul 4, 2026 12:00:00 AM EDT'))).toBe('2026-07-04');
  });

  it('treats an empty date as not stated', () => {
    expect(unwrapOrThrow(parseGrantsGovDate(''))).toBeNull();
    expect(unwrapOrThrow(parseGrantsGovDate(null))).toBeNull();
  });

  it('fails on a format it does not recognise rather than inventing a deadline', () => {
    expect(parseGrantsGovDate('sometime next spring').ok).toBe(false);
  });
});
